import { randomUUID } from 'crypto';

import { Gender, ProductActivityStatus, ProductStatus } from '~/common/enums';

enum UserRole {
  VENDOR = 'vendor',
}

const colorsSeedData = [
  { id: 1, name: 'Red' },
  { id: 2, name: 'Orange' },
  { id: 3, name: 'Yellow' },
  { id: 4, name: 'Green' },
  { id: 5, name: 'Blue' },
  { id: 6, name: 'White' },
  { id: 7, name: 'Black' },
];

const typesSeedData = [
  { id: 1, name: "T-shirts" },
  { id: 2, name: "Jeans" },
  { id: 3, name: "Dresses" },
  { id: 4, name: "Shirts and Blouses" },
  { id: 5, name: "Tops" },
  { id: 6, name: "Pants and Trousers" },
  { id: 7, name: "Skirts" },
  { id: 8, name: "Sweaters" },
  { id: 9, name: "Coats" },
  { id: 10, name: "Activewear" },
  { id: 11, name: "Sleepwear" },
  { id: 12, name: "Underwear" },
  { id: 13, name: "Swimwear" },
  { id: 14, name: "Sweatshirts" },
  { id: 15, name: "Suits" },
  { id: 16, name: "Maternity Wear" },
  { id: 17, name: "Plus-size Clothing" },
  { id: 18, name: "Ethnic Clothing" },
  { id: 19, name: "Sneakers" },
  { id: 20, name: "Boots" },
  { id: 21, name: "Sandals" },
  { id: 22, name: "Heels" },
  { id: 23, name: "Flats" },
  { id: 24, name: "Loafers" },
  { id: 25, name: "Moccasins" },
  { id: 26, name: "Slippers" },
  { id: 27, name: "Flip-flops" },
  { id: 28, name: "High heels" },
  { id: 29, name: "Handbags" },
  { id: 30, name: "Purses" },
  { id: 31, name: "Wallets" },
  { id: 32, name: "Clutches" },
  { id: 33, name: "Crossbody Bags" },
  { id: 34, name: "Hats" },
  { id: 35, name: "Belts" },
  { id: 36, name: "Jewelry" },
  { id: 37, name: "Watches" },
  { id: 38, name: "Sunglasses" },
  { id: 39, name: "Gloves" },
  { id: 40, name: "Ties" },
  { id: 41, name: "Brooches" },
];

const categoriesSeedData = [
  {
    id: 1,
    name: 'Clothing',
    styles: [1, 2, 6, 3, 4, 5],
    types: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
    brands: [19, 20, 21, 16, 12],
    materials: [1, 8, 9, 5, 4]
  },
  {
    id: 2,
    name: 'Accessories',
    styles: [1, 2, 6, 7, 8],
    types: [34, 35, 36, 37, 38, 39, 40, 41],
    brands: [4, 6, 7, 3, 8],
    materials: [2, 6, 1]
  },
  {
    id: 3,
    name: 'Bags',
    styles: [1, 2, 6, 9, 8],
    types: [29, 30, 31, 32, 33],
    brands: [9, 17, 18, 11, 10],
    materials: [2, 6, 7, 8]
  },
  {
    id: 4,
    name: 'Shoes',
    styles: [1, 2, 6, 9, 8],
    types: [19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
    brands: [5, 2, 13, 14, 15],
    materials: [2, 10, 6]
  },
  {
    id: 5,
    name: 'Designers',
    styles: [1, 2, 6, 3, 4, 5],
    types: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    brands: [22, 23, 24, 8, 25],
    materials: [6, 2, 1]
  },
];

const sizesSeedData = [
  { id: 1, name: 'XS' },
  { id: 2, name: 'S' },
  { id: 3, name: 'M' },
  { id: 4, name: 'L' },
  { id: 5, name: 'XL' },
  { id: 6, name: '40' },
  { id: 7, name: '42' },
  { id: 8, name: '43' },
];

const stylesSeedData = [
  { id: 1, name: 'Essentials' },
  { id: 2, name: 'Casual' },
  { id: 3, name: 'Event Dressing' },
  { id: 4, name: 'Wedding Guest' },
  { id: 5, name: 'Street style' },
  { id: 6, name: "Formal" },
  { id: 7, name: "Statement" },
  { id: 8, name: "Vintage" },
  { id: 9, name: "Trendy" },
];

const brandsSeedData = [
  { id: 1, name: 'H&M' },
  { id: 2, name: 'Adidas' },
  { id: 3, name: 'Prada' },
  { id: 4, name: 'Gucci' },
  { id: 5, name: 'Nike' },
  { id: 6, name: 'Chanel' },
  { id: 7, name: 'Louis Vuitton' },
  { id: 8, name: 'Versace' },
  { id: 9, name: 'Coach' },
  { id: 10, name: 'Tory Burch' },
  { id: 11, name: 'Longchamp' },
  { id: 12, name: 'Gap' },
  { id: 13, name: 'Converse' },
  { id: 14, name: 'Vans' },
  { id: 15, name: 'Reebok' },
  { id: 16, name: 'Levi\'s' },
  { id: 17, name: 'Kate Spade' },
  { id: 18, name: 'Michael Kors' },
  { id: 19, name: 'Ralph Lauren' },
  { id: 20, name: 'Calvin Klein' },
  { id: 21, name: 'Tommy Hilfiger' },
  { id: 22, name: 'Dolce & Gabbana' },
  { id: 23, name: 'Fendi' },
  { id: 24, name: 'Givenchy' },
  { id: 25, name: 'Armani' },
];

const materialsSeedData = [
  { id: 1, name: 'Cotton' },
  { id: 2, name: 'Leather' },
  { id: 3, name: 'denim' },
  { id: 4, name: 'Wool' },
  { id: 5, name: 'Silk' },
  { id: 6, name: 'Fabric' },
  { id: 7, name: 'Nylon' },
  { id: 8, name: 'Polyester' },
  { id: 9, name: 'Rayon' },
  { id: 10, name: 'Rubber' },
];

const imageSeedData = [
  {
    id: 1,
    url: 'https://thumbs.dreamstime.com/z/photography-woman-wearing-green-dress-114378751.jpg',
    description: 'green dress',
    created_at: new Date(2024, 2, 15),
    product_id: 1,
  },
  {
    id: 2,
    url: 'https://thumbs.dreamstime.com/z/leather-shoes-26612971.jpg?ct=jpeg',
    description: 'shoes',
    created_at: new Date(2024, 3, 15),
    product_id: 2,
  },
  {
    id: 3,
    url: 'https://thumbs.dreamstime.com/z/chino-pants-24575402.jpg?ct=jpeg',
    description: 'pants',
    created_at: new Date(2024, 2, 6),
    product_id: 3,
  },
  {
    id: 4,
    url: 'https://thumbs.dreamstime.com/z/long-pants-10608909.jpg?w=576',
    description: 'pants',
    created_at: new Date(2024, 2, 6),
    product_id: 3,
  },
  {
    id: 5,
    url: 'https://thumbs.dreamstime.com/z/mens-pants-isolated-white-background-dress-trousers-against-98716291.jpg?ct=jpeg',
    description: 'pants',
    created_at: new Date(2024, 2, 6),
    product_id: 3,
  },
  {
    id: 6,
    url: 'https://thumbs.dreamstime.com/b/nike-sport-shoes-18343734.jpg?w=768',
    description: 'nike',
    created_at: new Date(2024, 2, 25),
    product_id: 4,
  },
  {
    id: 7,
    url: 'https://thumbs.dreamstime.com/z/portrait-glamorous-lady-fashion-accessories-watches-red-cl-clutch-blue-background-48621018.jpg?ct=jpeg',
    description: 'red bag',
    created_at: new Date(2024, 4, 25),
    product_id: 5,
  },
  {
    id: 8,
    url: 'https://thumbs.dreamstime.com/z/colorful-makeup-hair-accessories-beauty-girl-portrait-32449784.jpg?ct=jpeg',
    description: 'accessory',
    created_at: new Date(2024, 4, 25),
    product_id: 6,
  },
];

const usersSeedData = [
  {
    id: randomUUID(),
    name: 'Joe Dou',
    email: 'vendor1@example.com',
    passwordHash: 'hashedpassword1',
    passwordSalt: 'saltsalt1',
    isActive: 'active',
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: randomUUID(),
    name: 'Ben Gran',
    email: 'vendor2@example.com',
    passwordHash: 'hashedpassword2',
    passwordSalt: 'saltsalt2',
    isActive: 'active',
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: randomUUID(),
    name: 'Vlad Manukian',
    email: 'react@example.com',
    passwordHash: 'hashedpassword2',
    passwordSalt: 'saltsalt2',
    isActive: 'active',
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: randomUUID(),
    name: 'Taras GAKMAN',
    email: 'next@example.com',
    passwordHash: 'hashedpassword2',
    passwordSalt: 'saltsalt2',
    isActive: 'active',
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: randomUUID(),
    name: 'User 1',
    email: 'user1@example.com',
    passwordHash: 'hashedpassword1',
    passwordSalt: 'saltsalt1',
    isActive: 'active',
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: randomUUID(),
    name: 'User 2',
    email: 'user2@example.com',
    passwordHash: 'hashedpassword2',
    passwordSalt: 'saltsalt2',
    isActive: 'active',
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: randomUUID(),
    name: 'User 3',
    email: 'user3@example.com',
    passwordHash: 'hashedpassword3',
    passwordSalt: 'saltsalt3',
    isActive: 'active',
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: randomUUID(),
    name: 'User 4',
    email: 'user4@example.com',
    passwordHash: 'hashedpassword4',
    passwordSalt: 'saltsalt4',
    isActive: 'active',
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: randomUUID(),
    name: 'User 5',
    email: 'user5@example.com',
    passwordHash: 'hashedpassword5',
    passwordSalt: 'saltsalt5',
    isActive: 'active',
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: randomUUID(),
    name: 'User 6',
    email: 'user6@example.com',
    passwordHash: 'hashedpassword6',
    passwordSalt: 'saltsalt6',
    isActive: 'active',
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: randomUUID(),
    name: 'User 7',
    email: 'user7@example.com',
    passwordHash: 'hashedpassword7',
    passwordSalt: 'saltsalt7',
    isActive: 'active',
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: randomUUID(),
    name: 'User 8',
    email: 'user8@example.com',
    passwordHash: 'hashedpassword8',
    passwordSalt: 'saltsalt8',
    isActive: 'active',
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: randomUUID(),
    name: 'User 9',
    email: 'user9@example.com',
    passwordHash: 'hashedpassword9',
    passwordSalt: 'saltsalt9',
    isActive: 'active',
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: randomUUID(),
    name: 'User 10',
    email: 'user10@example.com',
    passwordHash: 'hashedpassword10',
    passwordSalt: 'saltsalt10',
    isActive: 'active',
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: randomUUID(),
    name: 'User 11',
    email: 'user11@example.com',
    passwordHash: 'hashedpassword11',
    passwordSalt: 'saltsalt11',
    isActive: 'active',
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: randomUUID(),
    name: 'User 12',
    email: 'user12@example.com',
    passwordHash: 'hashedpassword12',
    passwordSalt: 'saltsalt12',
    isActive: 'active',
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: randomUUID(),
    name: 'User 13',
    email: 'user13@example.com',
    passwordHash: 'hashedpassword13',
    passwordSalt: 'saltsalt13',
    isActive: 'active',
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: randomUUID(),
    name: 'User 14',
    email: 'user14@example.com',
    passwordHash: 'hashedpassword14',
    passwordSalt: 'saltsalt14',
    isActive: 'active',
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: randomUUID(),
    name: 'User 15',
    email: 'user15@example.com',
    passwordHash: 'hashedpassword15',
    passwordSalt: 'saltsalt15',
    isActive: 'active',
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: randomUUID(),
    name: 'User 16',
    email: 'user16@example.com',
    passwordHash: 'hashedpassword16',
    passwordSalt: 'saltsalt16',
    isActive: 'active',
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: randomUUID(),
    name: 'User 17',
    email: 'user17@example.com',
    passwordHash: 'hashedpassword17',
    passwordSalt: 'saltsalt17',
    isActive: 'active',
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
];

const profilesSeedData = [
  {
    id: randomUUID(),
    user_id: usersSeedData[0].id,
    role: UserRole.VENDOR,
    phoneNumber: '123456789',
    profilePhoto:
      'https://thumbs.dreamstime.com/z/red-smiley-face-1839222.jpg?ct=jpeg',
    addressLineOne: '123 Vendor Street',
    addressLineTwo: '',
    country: 'Country',
    state: 'State',
    city: 'City',
    clothesSize: 'XL',
    jeansSize: '34',
    shoeSize: '10',
    isRegistrationCompleted: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: randomUUID(),
    user_id: usersSeedData[1].id,
    role: UserRole.VENDOR,
    phoneNumber: '987654321',
    profilePhoto:
      'https://thumbs.dreamstime.com/z/beautiful-pleased-smiling-cartoon-brunette-girl-dark-chocolate-hair-portrait-isolated-white-background-beautiful-pleased-188685252.jpg?ct=jpeg',
    addressLineOne: '456 Vendor Avenue',
    addressLineTwo: 'Apt 200',
    country: 'Country',
    state: 'State',
    city: 'City',
    clothesSize: 'L',
    jeansSize: '32',
    shoeSize: '9',
    isRegistrationCompleted: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: randomUUID(),
    user_id: usersSeedData[4].id,
    role: UserRole.VENDOR,
    phoneNumber: '3805083161221',
    profilePhoto:
      'https://thumbs.dreamstime.com/z/beautiful-pleased-smiling-cartoon-brunette-girl-dark-chocolate-hair-portrait-isolated-white-background-beautiful-pleased-188685252.jpg?ct=jpeg',
    addressLineOne: '456 Vendor Avenue',
    addressLineTwo: 'Apt 200',
    country: 'Country',
    state: 'State',
    city: 'City',
    clothesSize: 'L',
    jeansSize: '32',
    shoeSize: '9',
    isRegistrationCompleted: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: randomUUID(),
    user_id: usersSeedData[3].id,
    role: UserRole.VENDOR,
    phoneNumber: '380504314265',
    profilePhoto:
      'https://thumbs.dreamstime.com/z/beautiful-pleased-smiling-cartoon-brunette-girl-dark-chocolate-hair-portrait-isolated-white-background-beautiful-pleased-188685252.jpg?ct=jpeg',
    addressLineOne: '456 Vendor Avenue',
    addressLineTwo: 'Apt 200',
    country: 'Country',
    state: 'State',
    city: 'City',
    clothesSize: 'L',
    jeansSize: '32',
    shoeSize: '9',
    isRegistrationCompleted: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Добавление профилей для новых пользователей
  {
    id: randomUUID(),
    user_id: usersSeedData[5].id,
    role: UserRole.VENDOR,
    phoneNumber: '987654321',
    profilePhoto:
      'https://thumbs.dreamstime.com/z/beautiful-pleased-smiling-cartoon-brunette-girl-dark-chocolate-hair-portrait-isolated-white-background-beautiful-pleased-188685252.jpg?ct=jpeg',
    addressLineOne: '456 Vendor Avenue',
    addressLineTwo: 'Apt 200',
    country: 'Country',
    state: 'State',
    city: 'City',
    clothesSize: 'L',
    jeansSize: '32',
    shoeSize: '9',
    isRegistrationCompleted: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: randomUUID(),
    user_id: usersSeedData[6].id,
    role: UserRole.VENDOR,
    phoneNumber: '123456789',
    profilePhoto:
      'https://thumbs.dreamstime.com/z/red-smiley-face-1839222.jpg?ct=jpeg',
    addressLineOne: '123 Vendor Street',
    addressLineTwo: '',
    country: 'Country',
    state: 'State',
    city: 'City',
    clothesSize: 'XL',
    jeansSize: '34',
    shoeSize: '10',
    isRegistrationCompleted: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: randomUUID(),
    user_id: usersSeedData[7].id,
    role: UserRole.VENDOR,
    phoneNumber: '987654321',
    profilePhoto:
      'https://thumbs.dreamstime.com/z/beautiful-pleased-smiling-cartoon-brunette-girl-dark-chocolate-hair-portrait-isolated-white-background-beautiful-pleased-188685252.jpg?ct=jpeg',
    addressLineOne: '456 Vendor Avenue',
    addressLineTwo: 'Apt 200',
    country: 'Country',
    state: 'State',
    city: 'City',
    clothesSize: 'L',
    jeansSize: '32',
    shoeSize: '9',
    isRegistrationCompleted: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: randomUUID(),
    user_id: usersSeedData[8].id,
    role: UserRole.VENDOR,
    phoneNumber: '123456789',
    profilePhoto:
      'https://thumbs.dreamstime.com/z/red-smiley-face-1839222.jpg?ct=jpeg',
    addressLineOne: '123 Vendor Street',
    addressLineTwo: '',
    country: 'Country',
    state: 'State',
    city: 'City',
    clothesSize: 'XL',
    jeansSize: '34',
    shoeSize: '10',
    isRegistrationCompleted: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: randomUUID(),
    user_id: usersSeedData[9].id,
    role: UserRole.VENDOR,
    phoneNumber: '987654321',
    profilePhoto:
      'https://thumbs.dreamstime.com/z/beautiful-pleased-smiling-cartoon-brunette-girl-dark-chocolate-hair-portrait-isolated-white-background-beautiful-pleased-188685252.jpg?ct=jpeg',
    addressLineOne: '456 Vendor Avenue',
    addressLineTwo: 'Apt 200',
    country: 'Country',
    state: 'State',
    city: 'City',
    clothesSize: 'L',
    jeansSize: '32',
    shoeSize: '9',
    isRegistrationCompleted: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: randomUUID(),
    user_id: usersSeedData[10].id,
    role: UserRole.VENDOR,
    phoneNumber: '987654321',
    profilePhoto:
      'https://thumbs.dreamstime.com/z/beautiful-pleased-smiling-cartoon-brunette-girl-dark-chocolate-hair-portrait-isolated-white-background-beautiful-pleased-188685252.jpg?ct=jpeg',
    addressLineOne: '456 Vendor Avenue',
    addressLineTwo: 'Apt 200',
    country: 'Country',
    state: 'State',
    city: 'City',
    clothesSize: 'L',
    jeansSize: '32',
    shoeSize: '9',
    isRegistrationCompleted: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: randomUUID(),
    user_id: usersSeedData[11].id,
    role: UserRole.VENDOR,
    phoneNumber: '987654321',
    profilePhoto:
      'https://thumbs.dreamstime.com/z/beautiful-pleased-smiling-cartoon-brunette-girl-dark-chocolate-hair-portrait-isolated-white-background-beautiful-pleased-188685252.jpg?ct=jpeg',
    addressLineOne: '456 Vendor Avenue',
    addressLineTwo: 'Apt 200',
    country: 'Country',
    state: 'State',
    city: 'City',
    clothesSize: 'L',
    jeansSize: '32',
    shoeSize: '9',
    isRegistrationCompleted: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: randomUUID(),
    user_id: usersSeedData[12].id,
    role: UserRole.VENDOR,
    phoneNumber: '987654321',
    profilePhoto:
      'https://thumbs.dreamstime.com/z/beautiful-pleased-smiling-cartoon-brunette-girl-dark-chocolate-hair-portrait-isolated-white-background-beautiful-pleased-188685252.jpg?ct=jpeg',
    addressLineOne: '456 Vendor Avenue',
    addressLineTwo: 'Apt 200',
    country: 'Country',
    state: 'State',
    city: 'City',
    clothesSize: 'L',
    jeansSize: '32',
    shoeSize: '9',
    isRegistrationCompleted: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: randomUUID(),
    user_id: usersSeedData[13].id,
    role: UserRole.VENDOR,
    phoneNumber: '987654321',
    profilePhoto:
      'https://thumbs.dreamstime.com/z/beautiful-pleased-smiling-cartoon-brunette-girl-dark-chocolate-hair-portrait-isolated-white-background-beautiful-pleased-188685252.jpg?ct=jpeg',
    addressLineOne: '456 Vendor Avenue',
    addressLineTwo: 'Apt 200',
    country: 'Country',
    state: 'State',
    city: 'City',
    clothesSize: 'L',
    jeansSize: '32',
    shoeSize: '9',
    isRegistrationCompleted: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: randomUUID(),
    user_id: usersSeedData[14].id,
    role: UserRole.VENDOR,
    phoneNumber: '987654321',
    profilePhoto:
      'https://thumbs.dreamstime.com/z/beautiful-pleased-smiling-cartoon-brunette-girl-dark-chocolate-hair-portrait-isolated-white-background-beautiful-pleased-188685252.jpg?ct=jpeg',
    addressLineOne: '456 Vendor Avenue',
    addressLineTwo: 'Apt 200',
    country: 'Country',
    state: 'State',
    city: 'City',
    clothesSize: 'L',
    jeansSize: '32',
    shoeSize: '9',
    isRegistrationCompleted: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: randomUUID(),
    user_id: usersSeedData[15].id,
    role: UserRole.VENDOR,
    phoneNumber: '987654321',
    profilePhoto:
      'https://thumbs.dreamstime.com/z/beautiful-pleased-smiling-cartoon-brunette-girl-dark-chocolate-hair-portrait-isolated-white-background-beautiful-pleased-188685252.jpg?ct=jpeg',
    addressLineOne: '456 Vendor Avenue',
    addressLineTwo: 'Apt 200',
    country: 'Country',
    state: 'State',
    city: 'City',
    clothesSize: 'L',
    jeansSize: '32',
    shoeSize: '9',
    isRegistrationCompleted: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: randomUUID(),
    user_id: usersSeedData[16].id,
    role: UserRole.VENDOR,
    phoneNumber: '987654321',
    profilePhoto:
      'https://thumbs.dreamstime.com/z/beautiful-pleased-smiling-cartoon-brunette-girl-dark-chocolate-hair-portrait-isolated-white-background-beautiful-pleased-188685252.jpg?ct=jpeg',
    addressLineOne: '456 Vendor Avenue',
    addressLineTwo: 'Apt 200',
    country: 'Country',
    state: 'State',
    city: 'City',
    clothesSize: 'L',
    jeansSize: '32',
    shoeSize: '9',
    isRegistrationCompleted: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: randomUUID(),
    user_id: usersSeedData[17].id,
    role: UserRole.VENDOR,
    phoneNumber: '987654321',
    profilePhoto:
      'https://thumbs.dreamstime.com/z/beautiful-pleased-smiling-cartoon-brunette-girl-dark-chocolate-hair-portrait-isolated-white-background-beautiful-pleased-188685252.jpg?ct=jpeg',
    addressLineOne: '456 Vendor Avenue',
    addressLineTwo: 'Apt 200',
    country: 'Country',
    state: 'State',
    city: 'City',
    clothesSize: 'L',
    jeansSize: '32',
    shoeSize: '9',
    isRegistrationCompleted: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: randomUUID(),
    user_id: usersSeedData[18].id,
    role: UserRole.VENDOR,
    phoneNumber: '987654321',
    profilePhoto:
      'https://thumbs.dreamstime.com/z/beautiful-pleased-smiling-cartoon-brunette-girl-dark-chocolate-hair-portrait-isolated-white-background-beautiful-pleased-188685252.jpg?ct=jpeg',
    addressLineOne: '456 Vendor Avenue',
    addressLineTwo: 'Apt 200',
    country: 'Country',
    state: 'State',
    city: 'City',
    clothesSize: 'L',
    jeansSize: '32',
    shoeSize: '9',
    isRegistrationCompleted: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: randomUUID(),
    user_id: usersSeedData[19].id,
    role: UserRole.VENDOR,
    phoneNumber: '987654321',
    profilePhoto:
      'https://thumbs.dreamstime.com/z/beautiful-pleased-smiling-cartoon-brunette-girl-dark-chocolate-hair-portrait-isolated-white-background-beautiful-pleased-188685252.jpg?ct=jpeg',
    addressLineOne: '456 Vendor Avenue',
    addressLineTwo: 'Apt 200',
    country: 'Country',
    state: 'State',
    city: 'City',
    clothesSize: 'L',
    jeansSize: '32',
    shoeSize: '9',
    isRegistrationCompleted: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const reviewsSeedData = [
  {
    id: 7,
    review:
      'This vendor provides outstanding service and high-quality products. I am thoroughly impressed with their professionalism and attention to detail. From start to finish, my experience with them has been nothing short of exceptional. I highly recommend their services to anyone looking for reliability and top-notch performance.',
    review_user_id: usersSeedData[0].id,
    reviewed_user_id: usersSeedData[1].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    review: `I have been consistently amazed by the excellent products offered by this vendor. Their attention to quality and customer satisfaction is truly commendable. Each time I order from them, I am met with products that exceed my expectations. I can confidently say that choosing this vendor was one of the best decisions I've made for my business.`,
    review_user_id: usersSeedData[0].id,
    reviewed_user_id: usersSeedData[1].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    review: `Great customer service and fast delivery. Their products are exactly as described and of excellent quality. I will definitely be ordering from them again!`,
    review_user_id: usersSeedData[0].id,
    reviewed_user_id: usersSeedData[1].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    review: `I am very pleased with my purchase. The vendor was responsive and helpful throughout the transaction. The product arrived on time and in perfect condition. Highly recommended!`,
    review_user_id: usersSeedData[0].id,
    reviewed_user_id: usersSeedData[1].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 11,
    review: `Top-notch service! The vendor exceeded my expectations with their prompt communication and high-quality products. I will definitely be a returning customer.`,
    review_user_id: usersSeedData[0].id,
    reviewed_user_id: usersSeedData[1].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 12,
    review: `Excellent products!`,
    review_user_id: usersSeedData[0].id,
    reviewed_user_id: usersSeedData[1].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const productsSeedData = [
  {
    id: 1,
    name: 'Green dress',
    description:
      'Elegant and flowing long green dress, perfect for formal occasions or a night out. Made from high-quality fabric that drapes beautifully, providing both comfort and style. Available in multiple sizes and colors.',
    gender: Gender.FEMALE,
    status: ProductStatus.FOR_RENT,
    activity_status: ProductActivityStatus.ACTIVE,
    min_price: 100,
    max_price: 150,
    category_id: 1,
    style_id: 1,
    type_id: 1,
    brand_id: 1,
    material_id: 1,
    user_id: usersSeedData[0].id,
    variants: [
      { size_id: 1, color_id: 1, quantity: 5 },
      { size_id: 2, color_id: 2, quantity: 3 },
      { size_id: 3, color_id: 3, quantity: 2 },
    ],
    created_at: new Date(2024, 4, 25),
    updated_at: new Date(),
  },
  {
    id: 2,
    name: 'Shoes',
    description:
      'High-quality shoes designed for both comfort and style. Ideal for everyday wear or special occasions. Available in various sizes and colors to suit different preferences. Durable and stylish footwear for men.',
    gender: Gender.MALE,
    status: ProductStatus.FOR_RENT,
    activity_status: ProductActivityStatus.ACTIVE,
    min_price: 200,
    max_price: 250,
    category_id: 4,
    style_id: 2,
    type_id: 2,
    brand_id: 5,
    material_id: 2,
    user_id: usersSeedData[0].id,
    variants: [
      { size_id: 6, color_id: 6, quantity: 5 },
      { size_id: 7, color_id: 5, quantity: 3 },
    ],
    created_at: new Date(2024, 5, 25),
    updated_at: new Date(),
  },
  {
    id: 3,
    name: 'Pants',
    description:
      'Stylish and comfortable pants for women. Perfect for both casual and formal settings. Made from premium materials that offer durability and a great fit. Available in multiple sizes and colors to match your wardrobe.',
    gender: Gender.FEMALE,
    status: ProductStatus.FOR_RENT,
    activity_status: ProductActivityStatus.ACTIVE,
    min_price: 200,
    max_price: 220,
    category_id: 1,
    style_id: 2,
    type_id: 2,
    brand_id: 4,
    material_id: 3,
    user_id: usersSeedData[0].id,
    variants: [
      { size_id: 1, color_id: 1, quantity: 5 },
      { size_id: 2, color_id: 2, quantity: 3 },
      { size_id: 4, color_id: 3, quantity: 3 },
    ],
    created_at: new Date(2024, 6, 25),
    updated_at: new Date(),
  },
  {
    id: 4,
    name: 'Shoes',
    description:
      'Stylish and comfortable pants for women. Perfect for both casual and formal settings. Made from premium materials that offer durability and a great fit. Available in multiple sizes and colors to match your wardrobe.',
    gender: Gender.MALE,
    status: ProductStatus.FOR_RENT,
    activity_status: ProductActivityStatus.ACTIVE,
    min_price: 150,
    max_price: 170,
    category_id: 4,
    style_id: 2,
    type_id: 2,
    brand_id: 4,
    material_id: 2,
    user_id: usersSeedData[1].id,
    variants: [
      { size_id: 6, color_id: 6, quantity: 5 },
      { size_id: 7, color_id: 4, quantity: 3 },
      { size_id: 8, color_id: 2, quantity: 3 },
    ],
    created_at: new Date(2024, 7, 25),
    updated_at: new Date(),
  },
  {
    id: 5,
    name: 'Red bag',
    description:
      'Chic and stylish red bag perfect for adding a pop of color to any outfit. Spacious and functional, ideal for daily use or special events. Made from high-quality materials, ensuring durability and a sleek look.',
    gender: Gender.FEMALE,
    status: ProductStatus.FOR_RENT,
    activity_status: ProductActivityStatus.ACTIVE,
    min_price: 250,
    max_price: 270,
    category_id: 3,
    style_id: 3,
    type_id: 3,
    brand_id: 3,
    material_id: 6,
    user_id: usersSeedData[1].id,
    variants: [{ color_id: 1, size_id: 1, quantity: 5 }],
    created_at: new Date(2024, 7, 25),
    updated_at: new Date(),
  },
  {
    id: 6,
    name: 'Accessory',
    description:
      'Elegant and versatile accessory to complement any outfit. Perfect for adding a touch of sophistication to your look. Available in various styles and colors to suit your personal taste. Made with high-quality materials for lasting use.',
    gender: Gender.FEMALE,
    status: ProductStatus.FOR_SALE,
    activity_status: ProductActivityStatus.ACTIVE,
    min_price: 50,
    max_price: 70,
    category_id: 2,
    style_id: 2,
    type_id: 2,
    brand_id: 4,
    material_id: 6,
    user_id: usersSeedData[1].id,
    variants: [{ color_id: 6, size_id: 8, quantity: 5 }],
    created_at: new Date(2024, 7, 25),
    updated_at: new Date(),
  },
];

export {
  brandsSeedData,
  colorsSeedData,
  categoriesSeedData,
  imageSeedData,
  materialsSeedData,
  profilesSeedData,
  productsSeedData,
  sizesSeedData,
  stylesSeedData,
  typesSeedData,
  reviewsSeedData,
  usersSeedData,
};
