const USER_PASSWORD_SALT_ROUNDS = 10;

const PRODUCTS_LIMIT = 10;
const PRODUCTS_OFFSET = 0;
const PRODUCT_DATE_RANGE_FORMAT = 'yyyy-MM-dd';

export {
  PRODUCT_DATE_RANGE_FORMAT,
  PRODUCTS_LIMIT,
  PRODUCTS_OFFSET,
  USER_PASSWORD_SALT_ROUNDS,
};
