import { MigrationInterface, QueryRunner } from 'typeorm';

export class CatsAutogeneratedId1716556299086 implements MigrationInterface {
  name = 'CatsAutogeneratedId1716556299086';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('ALTER TABLE `cats` DROP PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `cats` DROP COLUMN `id`');
    await queryRunner.query(
      'ALTER TABLE `cats` ADD `id` int NOT NULL PRIMARY KEY AUTO_INCREMENT',
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('ALTER TABLE `cats` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `cats` ADD `id` int NOT NULL');
    await queryRunner.query('ALTER TABLE `cats` ADD PRIMARY KEY (`id`)');
  }
}
